app:
  port: 3000

facebook:
  access_token: EAAGeqaVIuesBAHI0gAVb2o6F43URGKZAgkaI7SWomh6MJGGZBDYuLVEHRZCNyU5rIWS9w9dJhZChzSQq9FnO8nY6ueZBN0OrRdjVgYkrcuWfz5LfhuFjxmb46ZAJoQelodRUEtSsSZBJDyGNWDIMVUk4f4aDclI8OirVsdOU6MIkfXUAS7hWCse
  verify_token: MESSENGER_CHATBOT
  uri: https://graph.facebook.com/v14.0/me/messages

database:
  uri: mongodb+srv://conghuy:conghuynt1999@cluster1.oq1l7.mongodb.net/chatbot
