app:
  port: 3000

facebook:
  access_token: EAAGeqaVIuesBAMwmUOCsGYdkpFmFFFYbIm8uMAZCqEdsUZCZAIEBw7OS8SV2GBVZBDLcv1PGnZCZCTgqrVKCINRIgUA6wGgEGvbTpgQ0kEHZBtgihv6UVVIcHuyXJejfvX1xyN8epZCF3pLN07q4UbsH01fZAdv8ZBnL1kEZAV6aGp5xVdCKZBtOvQZAy
  verify_token: MESSENGER_CHATBOT
  message_uri: https://graph.facebook.com/v14.0/me/messages
  wit_token: UJ3ENGWTQOI7KOPA5G3ZEVDWUHJCOJFA
  wit_version: 20220813
  wit_uri: https://api.wit.ai

database:
  uri: mongodb+srv://conghuy:conghuynt1999@cluster1.oq1l7.mongodb.net/messenger_chatbot
