app:
  port: 3000

facebook:
  access_token: EAAGeqaVIuesBADNQgVSz553HMM4kEVv0gnkYEnDFgtcZBybSAHbOkcL4ZCFm9sZCth5qIhDeJBJMcncLS8ZAIsKoZBX8tydIUnkgwkdbtC4IWvXsQPRFbsvklNTkDaRG6NaKfQz2DlXZCzS3PnhagskY9hXS2EG4Lpd3DcJBqzNkCEXoD09tfr
  verify_token: MESSENGER_CHATBOT
  uri: https://graph.facebook.com/v14.0/me/messages

database:
  uri: mongodb+srv://conghuy:conghuynt1999@cluster1.oq1l7.mongodb.net/chatbot
