app:
  port: 3000

facebook:
  access_token: EAAGeqaVIuesBAHa7FSbS2MkQN8ky99Ri00W06FRW0goySv6xyjH8epjB03yVfb6gNcpwRBseZA0w4bFZCTzHZBa4DkYZBjHfCt4blNKbcwfhzR5m7HFegmlu2wNFCJnZAo5yoWkb6gsBgkbLqFOoOjZAPMnc8AuljMwKbUfFJChd3mNRkjpmzu
  verify_token: MESSENGER_CHATBOT
  uri: https://graph.facebook.com/v14.0/me/messages

database:
  uri: mongodb+srv://conghuy:conghuynt1999@cluster1.oq1l7.mongodb.net/chatbot
