app:
  port: 3000

facebook:
  access_token: EAAGeqaVIuesBAOBCfTSHu8yMYFmQmLlaNZBgWW3NUWmKmNVCNOJozja9VZByRLFLimiviZADzdXwjZB3BieVwm5gWt2rznEitcLZCeSaLntAmrjGXyRaHPxZBLeXNW5tsnwhFZAFBT7lmZBOEpXVcHcEY3Vo28ZAWfuCFFDyLnKgtkHkeRiZBThzdm
  verify_token: MESSENGER_CHATBOT
  uri: https://graph.facebook.com/v14.0/me/messages

database:
  uri: mongodb+srv://conghuy:conghuynt1999@cluster1.oq1l7.mongodb.net/chatbot
